keys:
  - &sre age1rj7vaq0rsarnum2fx6zq0k3l64f6mca9t9mlhqu4nfvpqhux6uts5zud2m
  - &preprod1-bp-a-1 age1zhewzr3r8u4qmu9c5asw0vv9pw9qxvah9y60reu5uggrr8vrd95skhn3q3
  - &preview1-bp-a-1 age10mgec0e4xp87x79fsd5r9pdggt8gr4mjpnj98zhlpvzx6almhd5sxrakyh
  - &sanchonet1-bp-a-1 age1apa4g9hfjaq9kp95utg5jeqm9zmdhylcfsqmekrl0ptg4wjt53fsrfffy9
  - &shelley-qa1-bp-a-1 age1e2lurmyrrsfmfen9dgmdkmjwgmfaz4y7ecysdtpc8pd9qr4htfasvs0az8
creation_rules:
  - path_regex: preprod1/[^/]+\.*$
    key_groups:
    - age:
      - *sre
      - *preprod1-bp-a-1
  - path_regex: preview1/[^/]+\.*$
    key_groups:
    - age:
      - *sre
      - *preview1-bp-a-1
  - path_regex: sanchonet1/[^/]+\.*$
    key_groups:
    - age:
      - *sre
      - *sanchonet1-bp-a-1
  - path_regex: shelley-qa1/[^/]+\.*$
    key_groups:
    - age:
      - *sre
      - *shelley-qa1-bp-a-1
