apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardano-test-node
  namespace: cardano-test-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardano-test-node
  template:
    metadata:
      labels:
        app: cardano-test-node
    spec:
      containers:
      - name: cardano-test-node
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: NETWORK
          value: test
        - name: PORT
          value: "3001"
        volumeMounts:
          - name: testnodeipc
            mountPath: /root/.local/share/cardano-playground.git
      volumes:
        - name: testnodeipc
          persistentVolumeClaim:
            claimName: ipc
      imagePullSecrets:
        - name: testcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cardano-test-node
  namespace: cardano-test-node
spec:
  selector:
    app: cardano-test-node
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  type: NodePort
