apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipc
  namespace: cardano-node-{{ .Values.network }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
