on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_ACCESS_TOKEN}}
          submodules: true
          persist-credentials: true
      - name: Checkout submodules using a PAT
        run: |
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile.yoroi-backend-zero
          tags: emurgornd/yoroi-backend-zero:${{ github.ref_name }}
          context: .

  pack-k8s-app:
    permissions:
      contents: read
      pull-requests: write
    uses: Emurgo/emurgo-deploy-utils/.github/workflows/pack-k8s-app.yaml@main
    with:
      app-name: yoroi-backend-zero
      octopus-project: yoroi-backend-zero
    secrets:
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
